### ISSUE TITLE
Orçamento e Preços > Formulários: Telefone aceitando numeros a menos e a mais

### ISSUE THREAD

**Issue by agabiabreu** [eticketa/site17#26]
Dentro de todos os formulários das seções de Orçamento e Preços o campo telefone está aceitando menos de 8 dígitos e mais de 9, o que não pode ocorrer.

**Comment by raphaelrpais** [comment]
Não sei se vc recebe notificação quando eu marco a issue num commit, por via das dúvidas: @agabiabreu

**Comment by agabiabreu** [comment]
Tô impressionada! Fez funcionar até se a pessoa tiver mania de colocar - ou espaço no local certinho!  @raphaelrpais 

Funcionando!
