### ISSUE TITLE
Orçamento > Formulários : Campo Dimensões não permite número maior que 99

### ISSUE THREAD

**Issue by agabiabreu** [eticketa/site17#29]
Em todos os formulários da seção Orçamento não é possível colocar um valor maior que 99, pois acima de 3 números o campo reclama que o campo deveria ter somente números.

**Comment by raphaelrpais** [comment]
@agabiabreu, dá um confere e, se estiver certo (aceitando 3 dígitos) transforma em **enhancement** para que a <pattern> aceite medidas só até (um pouco mais que) os limites das máquinas.

**Comment by agabiabreu** [comment]
@raphaelrpais Esse não tá funfando não =(

![image](https://user-images.githubusercontent.com/26579314/31740809-22e95a16-b431-11e7-80f8-8ffb8cf741d7.png)

**Comment by raphaelrpais** [comment]
@agabiabreu , testa de novo aí... Aqui tá direito sim, talvez tenha demorado pra replicar essa parte.

**Comment by agabiabreu** [comment]
Opa! Agora atualizou e tá ok!
