### ISSUE TITLE
Contato > Formulário da direita : Campo telefone não informa o erro exato

### ISSUE THREAD

**Issue by agabiabreu** [eticketa/site17#36]
Ao digitar caracteres, o campo deveria apresentar erros de só utilizar números e ao digitar telefone sem o DDD informar o formato desejado.

**Comment by raphaelrpais** [comment]
Não sei se vc recebe notificação quando eu marco a issue num commit, por via das dúvidas: @agabiabreu

**Comment by agabiabreu** [comment]
Funcionando!
