### ISSUE TITLE
Adicionar um botão de voltar ao topo do site

### ISSUE THREAD

**Issue by agabiabreu** [eticketa/site17#37]
Acho interessante, mesmo sabendo q no Menu há possibilidade de voltar à Página Inicial.

**Comment by agabiabreu** [comment]
@raphaelrpais depois ve se faz sentido ou não, se achar, tira a label "question", se não fizer sentido, pode fechar.

**Comment by raphaelrpais** [comment]
@agabiabreu , não gosto...
