### ISSUE TITLE
<form> precisa entender PT-br e HTML

### ISSUE THREAD

**Issue by raphaelrpais** [eticketa/site17#9]
Referências:
[php.net](http://php.net/manual/en/function.mail.php/#example-3933)

Começaria simplesmente trocando a ordem no fim do PHP, colocando os `$headers` antes antes do `$to`.

Outra possibilidade `$mensagem = utf8_encode($mensagem);`.
[último exemplo do link](https://www.scriptbrasil.com.br/forum/topic/161070-resolvido%C2%A0ajuda-com-acentos-em-formulario-com-php/)

**Comment by raphaelrpais** [comment]
Só falta fazer com que o **assunto** também entenda os acentos.

**Comment by agabiabreu** [comment]
Uhuuuuuuuuul!!!!!

Em 5 de set de 2017 5:15 PM, "Raphael Pais" <notifications@github.com>
escreveu:
